import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import ReduxToolkitProvider, {
  PersistGateProvider,
} from "@/redux/reduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased mt-[110px]">
        <Toaster />
        <ReduxToolkitProvider>
          <PersistGateProvider>
            <Header />
            <Toaster />
            {/* Wrap children with main */}
            <main>{children}</main>
          </PersistGateProvider>
          <Footer />
        </ReduxToolkitProvider>
        {/* Place the Footer outside of the page content */}
      </body>
    </html>
  );
}
